<?php

use Illuminate\Database\Seeder;
use App\Models\MasterDataCctv;


class MasterDataCctvSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        MasterDataCctv::truncate();

        $cctv = [

            [
                "lokasi" => "A Yani",
                "latitude" => "-6.913483",
                "longitude" => "107.634377",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" =>  "Braga",
                "latitude" => "-6.916200",
                "longitude" => "107.609051",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" =>  "Cendana",
                "latitude" => "-6.909322",
                "longitude" => "107.627686",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Dalem kaum",
                "latitude" => "-6.922317",
                "longitude" => "107.606228",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Husein",
                "latitude" => "-6.906791",
                "longitude" => "107.587603",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Jl. Jakarta",
                "latitude" => "-6.913799",
                "longitude" => "107.643679",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Cikawao",
                "latitude" => "-6.928698",
                "longitude" => "107.616431",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Merdeka Aceh",
                "latitude" => "-6.909785",
                "longitude" => "107.610550",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Merdeka Jawa",
                "latitude" => "-6.913623",
                "longitude" => "107.610419",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "BKR",
                "latitude" => "-6.937549",
                "longitude" => "107.606267",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Inhoftank",
                "latitude" => "-6.937248",
                "longitude" => "107.603039",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Peta",
                "latitude" => "-6.926868",
                "longitude" => "107.585472",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Riau Banda",
                "latitude" => "-6.906076",
                "longitude" => "107.616864",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Gerlong",
                "latitude" => "-6.864773",
                "longitude" => "107.594244",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Buah Batu",
                "latitude" => "-6.948019",
                "longitude" => "107.633248",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Soeta Kircon",
                "latitude" => "-6.945341",
                "longitude" => "107.641785",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Suniaraja",
                "latitude" => "-6.915771",
                "longitude" => "107.604414",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Simpang IP",
                "latitude" => "-6.906372",
                "longitude" => "107.597659",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Alun alun Bandung",
                "latitude" => "-6.923347",
                "longitude" => "107.606226",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Kordon",
                "latitude" => "-6.954143",
                "longitude" => "107.640162",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Ciateul",
                "latitude" => "-6.931781",
                "longitude" => "107.606730",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Cicabe",
                "latitude" => "-6.902297",
                "longitude" => "107.659614",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Gateway",
                "latitude" => "-6.907154",
                "longitude" => "107.646199",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Cihampelas",
                "latitude" => "-6.900462",
                "longitude" => "107.604255",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Cimindi Jembatan",
                "latitude" => "-6.896405",
                "longitude" => "107.560650",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Cimindi Kharisma",
                "latitude" => "-6.899308",
                "longitude" => "107.562477",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Cimindi Sukaraja",
                "latitude" => "-6.895404",
                "longitude" => "107.560235",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Dago",
                "latitude" => "-6.885117",
                "longitude" => "107.613674",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Gasibu",
                "latitude" => "-6.899216",
                "longitude" => "107.619543",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Gedebage",
                "latitude" => "-6.941058",
                "longitude" => "107.691891",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Jakarta HKBP",
                "latitude" => "-6.914577",
                "longitude" => "107.635508",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Jamika",
                "latitude" => "-6.920282",
                "longitude" => "107.586254",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Katamso Perempatan Pahlawan",
                "latitude" => "-6.897708",
                "longitude" => "107.634135",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Kebon Kopi",
                "latitude" => "-6.904820",
                "longitude" => "107.565701",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Kircon",
                "latitude" => "-6.918713",
                "longitude" => "107.644202",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Pasteur",
                "latitude" => "-6.900444",
                "longitude" => "107.597944",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Sukajadi-Hasan Sadikin",
                "latitude" =>    "-6.89697",
                "longitude" => "107.597289",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Surapati core",
                "latitude" => "-6.901857",
                "longitude" => "107.652617",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Tegalega",
                "latitude" => "-6.933625",
                "longitude" => "107.603273",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "A Yani - Laswi",
                "latitude" => "-6.918676",
                "longitude" => "107.631394",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Batas Kota",
                "latitude" => "-6.910573",
                "longitude" => "107.569273",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Kebon Kawung Paskal",
                "latitude" => "-6.912358",
                "longitude" => "-6.912358",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Cicendo Kb. Kawung",
                "latitude" => "-6.912707",
                "longitude" => "107.60396",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Pasar Pagarsih",
                "latitude" => "-6.922584",
                "longitude" => "107.592571",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Taman Sari - Dayang Sumbi",
                "latitude" => "-6.887389",
                "longitude" => "107.611412",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Depan Toko Indra (Alun-Alun)",
                "latitude" => "-6.921128",
                "longitude" => "107.606552",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "ITB Kebun Binatang",
                "latitude" => "-6.893867",
                "longitude" => "107.608454",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "ITC Kebon Kalapa",
                "latitude" => "-6.927394",
                "longitude" => "107.605738",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Jalaprang",
                "latitude" => "-6.898527",
                "longitude" => "107.631864",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Jl. Anggrek",
                "latitude" => "-6.909711",
                "longitude" => "107.632042",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Jl. Arcamanik",
                "latitude" => "-6.904945",
                "longitude" => "107.673101",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Jl.Cihapit",
                "latitude" => "-6.909156",
                "longitude" => "107.621112",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Jl. Surya Sumantri",
                "latitude" => "-6.882385",
                "longitude" => "107.581539",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Jl .sutami",
                "latitude" => "-6.880703",
                "longitude" => "107.578661",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Jl. Turangga",
                "latitude" => "-6.929088",
                "longitude" => "107.635544",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Katamso",
                "latitude" => "-6.903044",
                "longitude" => "107.633035",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Pasar Kosambi",
                "latitude" => "-6.919720",
                "longitude" => "107.622499",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Pusdai",
                "latitude" => "-6.901174",
                "longitude" => "107.625363",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Sukajadi - Setiabudhi",
                "latitude" => "-6.878198",
                "longitude" => "107.597821",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Surapati Gasibu",
                "latitude" => "-6.898899",
                "longitude" => "107.616002",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Taman Pramuka",
                "latitude" => "-6.910142",
                "longitude" => "107.626063",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Taman Sari WS",
                "latitude" => "-6.900525",
                "longitude" => "107.609357",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Taman Sumbersari",
                "latitude" => "-6.932122",
                "longitude" => "107.576374",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Kopo Bizpark",
                "latitude" => "-6.951227",
                "longitude" => "107.585942",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Alun-Alun Ujung Berung",
                "latitude" => "-6.913668",
                "longitude" => "107.701545",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "JL. AHMAD YANI PERTIGAAN MALABAR",
                "latitude" => "-6.918710",
                "longitude" => "107.624248",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "JL. ASIA AFRIKA BRI TOWER",
                "latitude" => "-6.921090",
                "longitude" => "107.607592",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "JL. ASIA AFRIKA SIMPANG BRAGA",
                "latitude" => "-6.921378",
                "longitude" => "107.609880",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "JL. CIGADUNG",
                "latitude" => "-6.886279",
                "longitude" => "107.626502",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "JL. CIKUTRA PERTIGAAN BOJONG KONENG",
                "latitude" => "-6.895863",
                "longitude" => "107.643424",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "JL. DJUNJUNAN BTC",
                "latitude" => "-6.892793",
                "longitude" => "107.585102",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "JL. IR. H. DJUANDA SIMPANG DAGO",
                "latitude" => "-6.884939",
                "longitude" => "107.613488",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "JL. KOPO SEBRANG MIKO MALL",
                "latitude" => "-6.960104",
                "longitude" => "107.580028",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "JL. MOH TOHA TEGALLEGA",
                "latitude" => "-6.931218",
                "longitude" => "107.607062",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Jl Otista Sebrang Pasar Baru",
                "latitude" => "-6.917377",
                "longitude" => "107.604776",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Jl. Perintis Kemerdekaan",
                "latitude" => "-6.914189",
                "longitude" => "107.607428",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Jl. Purnawarman BEC",
                "latitude" => "-6.908975",
                "longitude" => "107.609369",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Jl.Soeta Metro Dealer Mercy",
                "latitude" => "-6.939068",
                "longitude" => "107.667488",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Jl. Sukajadi PVJ",
                "latitude" => "-6.889107",
                "longitude" => "107.596953",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Jl. Terusan Buah Batu",
                "latitude" => "-6.965207",
                "longitude" => "107.637852",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Jl. Tubagus Ismail",
                "latitude" => "-6.885059",
                "longitude" => "107.619762",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Jl. Waas Pertigaan Komplek Batununggal",
                "latitude" => "-6.951555",
                "longitude" => "107.626960",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Taman Tongkeng",
                "latitude" => "-6.911651",
                "longitude" => "107.623386",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Babakan Siliwangi (di Kel. Lebak Siliwangi)",
                "latitude" => "-6.884810",
                "longitude" => "107.611054",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],

            [
                "lokasi" => "Babakan Siliwangi (Pintu Forest Walk)",
                "latitude" => "-6.884909",
                "longitude" => "107.608942",
                "dinas" => "DISKOMINFO",
                "status" => "1",
                "link_stream" => "",
                "vendor" => "",
            ],
            [
                "lokasi" => "CCTV PUSDAI 02",
                "vendor" => "Dahua",
                "latitude" => "-6.901174",
                "longitude" => "107.626364",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/Pusda.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV TERMINAL DAGO 01",
                "vendor" => "Hikviksion",
                "latitude" => "-6.866827",
                "longitude" => "107.620672",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/HIKSVISION/IrHJuandaTerminaldago.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV SEBRANG PASAR BARU 01",
                "vendor" => "Hikviksion",
                "latitude" => "-6.917858",
                "longitude" => "107.603894",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/HIKSVISION/Otistasebrangpasarbaru.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV BATAS KOTA 02",
                "vendor" => "Dahua",
                "latitude" => "-6.910573",
                "longitude" => "107.568274",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/BatasKota.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV ALUN-ALUN_02 ",
                "vendor" => "Dahua",
                "latitude" => "-6.923347",
                "longitude" => "107.607227",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/ALU.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV ALUN-ALUN_03 ",
                "vendor" => "Dahua",
                "latitude" => "-6.923347",
                "longitude" => "107.608228",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/ALUN.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV JL. SURYA SUMANTRI 01",
                "vendor" => "Dahua",
                "latitude" => "-6.882717",
                "longitude" => "107.581503",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/Suryamantri.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV PUSDAI 01",
                "vendor" => "Dahua",
                "latitude" => "-6.901174",
                "longitude" => "107.625363",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/Pusdai.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV CIATEUL_01 ",
                "vendor" => "Hikviksion",
                "latitude" => "-6.931781",
                "longitude" => "107.606732",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/CIAT.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV JL ASIA AFRIKA BRI TOWER 02",
                "vendor" => "Hikviksion",
                "latitude" => "-6.920885",
                "longitude" => "107.606678",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/HIKSVISION/AsiaAfrikaBRITowerdua.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV PASAR KOSAMBI 02",
                "vendor" => "Dahua",
                "latitude" => "-6.919723",
                "longitude" => "107.623498",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/PasarKomb.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV JL. SURYA SUMANTRI 02",
                "vendor" => "Dahua",
                "latitude" => "-6.882717",
                "longitude" => "107.582504",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/Sury.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV JL ASIA AFRIKA BRI TOWER 03",
                "vendor" => "Hikviksion",
                "latitude" => "-6.920885",
                "longitude" => "107.606778",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/HIKSVISION/AsiaAfrikaBRITowertiga.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV KATAMSO 02",
                "vendor" => "Dahua",
                "latitude" => "-6.903044",
                "longitude" => "107.634036",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/Katamsoke.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV GASIBU_01 ",
                "vendor" => "Dahua",
                "latitude" => "-6.899248",
                "longitude" => "107.619846",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/GASIBU.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV TERMINAL DAGO 02",
                "vendor" => "Hikviksion",
                "latitude" => "-6.8668278",
                "longitude" => "107.6207728",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/HIKSVISION/IrHJuandaTerminaldagodua.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV JAKARTA-HKBP_01 ",
                "vendor" => "Hikviksion",
                "latitude" => "-6.914577",
                "longitude" => "107.635508",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/JAKA.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV KATAMSO-PAHLAWAN_03 ",
                "vendor" => "Dahua",
                "latitude" => "-6.897708",
                "longitude" => "107.636137",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/KATA.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV KEBON-KOPI-CIMAHI ",
                "vendor" => "Dahua",
                "latitude" => "-6.9021937",
                "longitude" => "107.563879",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/KEBON.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV JL WAAS BATUNUNGGAL 01",
                "vendor" => "Hikviksion",
                "latitude" => "-6.9507516",
                "longitude" => "107.6266188",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/HIKSVISION/WaaspertigaankompleksBatununggal.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV KEBON-KOPI_BANDUNG ",
                "vendor" => "Dahua",
                "latitude" => "-6.90482",
                "longitude" => "107.566702",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/KEBO.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV CICENDO - KB KAWUNG 03",
                "vendor" => "Dahua",
                "latitude" => "-6.912707",
                "longitude" => "107.605964",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/Cicen.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV CICENDO - KB KAWUNG 01",
                "vendor" => "Dahua",
                "latitude" => "-6.912707",
                "longitude" => "107.604962",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/Cicendo.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV JL. SUTAMI 01",
                "vendor" => "Dahua",
                "latitude" => "-6.880703",
                "longitude" => "107.578661",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/Sutami.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV TAMAN SARI - WS 01",
                "vendor" => "Dahua",
                "latitude" => "-6.900525",
                "longitude" => "107.609357",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/Tamansr.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV TAMAN SARI - WS 02",
                "vendor" => "Dahua",
                "latitude" => "-6.900525",
                "longitude" => "107.608358",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/Tamansri.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV JL. SURAPATI - GASIBU 01",
                "vendor" => "Dahua",
                "latitude" => "-6.898899",
                "longitude" => "107.616002",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/Surat.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV YANI - LASWI 01",
                "vendor" => "Dahua",
                "latitude" => "-6.918676",
                "longitude" => "107.631394",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/Yanilaswi.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV DEPAN TOKO INDRA (ALUN2) 01",
                "vendor" => "Dahua",
                "latitude" => "-6.9211119",
                "longitude" => "107.606447",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/DepanTo.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV KATAMSO 01",
                "vendor" => "Dahua",
                "latitude" => "-6.903044",
                "longitude" => "107.633035",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/Katamsok.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV JL. CIHAPIT 01",
                "vendor" => "Dahua",
                "latitude" => "-6.909156",
                "longitude" => "107.621112",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/Cihapit.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV KEBON KAWUNG - PASKAL 01",
                "vendor" => "Dahua",
                "latitude" => "-6.912358",
                "longitude" => "107.598068",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/KebonKam.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV PASAR KOSAMBI 01",
                "vendor" => "Dahua",
                "latitude" => "-6.91972",
                "longitude" => "107.622499",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/PasarKosam.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV JL. SUTAMI 02",
                "vendor" => "Dahua",
                "latitude" => "-6.880703",
                "longitude" => "107.577662",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/Suta.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV DEPAN TOKO INDRA (ALUN2) 02",
                "vendor" => "Dahua",
                "latitude" => "-6.9211119",
                "longitude" => "107.607448",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/DepanTop.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV BATAS KOTA 01",
                "vendor" => "Dahua",
                "latitude" => "-6.910573",
                "longitude" => "107.569273",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/BatasKo.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV JL. CIHAPIT 02",
                "vendor" => "Dahua",
                "latitude" => "-6.909156",
                "longitude" => "107.622113",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/Ciha.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV KEBON KAWUNG - PASKAL 02",
                "vendor" => "Dahua",
                "latitude" => "-6.912358",
                "longitude" => "107.597069",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/KebonKa.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV CICENDO - KB KAWUNG 02",
                "vendor" => "Dahua",
                "latitude" => "-6.912707",
                "longitude" => "107.603963",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/Cicend.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV SIMPANG BRAGA 03",
                "vendor" => "Hikviksion",
                "latitude" => "-6.921271",
                "longitude" => "107.608966",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/HIKSVISION/AsiaAfrikaSimpangBragatiga.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV JALAPRANG 01",
                "vendor" => "Dahua",
                "latitude" => "-6.898527",
                "longitude" => "107.631864",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/Jalaprang.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV JL CIGADUNG 01",
                "vendor" => "Hikviksion",
                "latitude" => "-6.8813198",
                "longitude" => "107.6249361",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/HIKSVISION/Cigadung.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV BALAIKOTA 01",
                "vendor" => "Hikviksion",
                "latitude" => "-6.91307842",
                "longitude" => "107.6091574",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/HIKSVISION/Balkot.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV BALAIKOTA 02",
                "vendor" => "Hikviksion",
                "latitude" => "-6.91307792",
                "longitude" => "107.6091574",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/HIKSVISION/Balaikota.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "CCTV MTOHA-BKR_01 ",
                "vendor" => "Dahua",
                "latitude" => "-6.937549",
                "longitude" => "107.606267",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DAHUA/Mohtohabkr.m3u8",
                "dinas" => "diskominfo",
            ],
            [
                "lokasi" => "TB JL. Pagarsih",
                "vendor" => "Hikviksion",
                "latitude" => "-6.922846",
                "longitude" => "107.595640",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DPU/pagarsih.m3u8",
                "dinas" => "DPU",
            ],
            [
                "lokasi" => "TB JL. Rumah Sakit",
                "vendor" => "Hikviksion",
                "latitude" => "-6.936589",
                "longitude" => "107.692645",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DPU/rumahsakit.m3u8",
                "dinas" => "DPU",
            ],
            [
                "lokasi" => "TB JL. Rumah Sakit 2",
                "vendor" => "Hikviksion",
                "latitude" => "-6.925072",
                "longitude" => "107.695595",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DPU/rumahsakit2.m3u8",
                "dinas" => "DPU",
            ],
            [
                "lokasi" => "TB JL. RAYA KOPO CITARIP",
                "vendor" => "Hikviksion",
                "latitude" => "-6.941369",
                "longitude" => "107.592361",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DPU/kopocitarip.m3u8",
                "dinas" => "DPU",
            ],
            [
                "lokasi" => "TB JL. SUKAMULYA",
                "vendor" => "Hikviksion",
                "latitude" => "-6.886724",
                "longitude" => "107.588118",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DPU/sukamulya.m3u8",
                "dinas" => "DPU",
            ],
            [
                "lokasi" => "TB JL. TRS. PASIRKOJA",
                "vendor" => "Hikviksion",
                "latitude" => "-6.930230",
                "longitude" => "107.576301",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DPU/trspasirkoja.m3u8",
                "dinas" => "DPU",
            ],
            [
                "lokasi" => "TB JL. CIKUTRA",
                "vendor" => "Hikviksion",
                "latitude" => "-6.900364",
                "longitude" => "107.643456",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DPU/cikutra.m3u8",
                "dinas" => "DPU",
            ],
            [
                "lokasi" => "TB JL CIBADUYUT",
                "vendor" => "Hikviksion",
                "latitude" => "-6.961357",
                "longitude" => "107.593967",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DPU/cibaduyut.m3u8",
                "dinas" => "DPU",
            ],
            [
                "lokasi" => "TB JL. A. H. NASUTION CIKADUT",
                "vendor" => "Hikviksion",
                "latitude" => "-6.904198",
                "longitude" => "107.666935",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DPU/cikadut.m3u8",
                "dinas" => "DPU",
            ],
            [
                "lokasi" => "TB JL. CIKUTRA BARAT",
                "vendor" => "Hikviksion",
                "latitude" => "-6.892253",
                "longitude" => "107.631744",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DPU/cikutrabarat.m3u8",
                "dinas" => "DPU",
            ],
            [
                "lokasi" => "TB JL. PETA - LW PANJANG",
                "vendor" => "Hikviksion",
                "latitude" => "-6.937612",
                "longitude" => "107.597090",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DPU/petalwpanjang.m3u8",
                "dinas" => "DPU",
            ],
            [
                "lokasi" => "TB IBRAHIM ADJIE",
                "vendor" => "Hikviksion",
                "latitude" => "-6.930877",
                "longitude" => "107.643784",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DPU/ibrahimadjie.m3u8",
                "dinas" => "DPU",
            ],
            [
                "lokasi" => "TB JL. GD BAGE SElatitudeAN - JL DERWATI",
                "vendor" => "Hikviksion",
                "latitude" => "-6.965546",
                "longitude" => "107.686892",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DPU/gdbageselatitudean.m3u8",
                "dinas" => "DPU",
            ],
            [
                "lokasi" => "TB JL. CINGISED",
                "vendor" => "Hikviksion",
                "latitude" => "-6.928615",
                "longitude" => "0",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DPU/cingised.m3u8",
                "dinas" => "DPU",
            ],
            [
                "lokasi" => "TB JL. TERUSAN JAKARTA - SUPERINDO",
                "vendor" => "Hikviksion",
                "latitude" => "-6.913679",
                "longitude" => "107.660248",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DPU/terusanjakarta.m3u8",
                "dinas" => "DPU",
            ],
            [
                "lokasi" => "TB JL. SUDIRMAN ",
                "vendor" => "Hikviksion",
                "latitude" => "-6.919084",
                "longitude" => "107.589778",
                "status" => "1",
                "link_stream" => "https://pelindung.bandung.go.id:3443/video/DPU/sudirman.m3u8",
                "dinas" => "DPU"
            ]
        ];
        MasterDataCctv::insert($cctv);
    }
}
